server:
  port: 8085
eureka:
  instance:
    hostname: 127.0.0.1
    #服务续约任务的调用间隔时间，默认为30秒
    lease-renewal-interval-in-seconds: 30
    #服务失效的时间，默认为90秒
    lease-expiration-duration-in-seconds: 90
  client:
    #不注册自己
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false